export const GET_DATA_REQ = "GET_DATA_REQ";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const ADD_DATA_TO_CART_REQ = "ADD_DATA_TO_CART_REQ";
export const ADD_DATA_TO_CART_SUCCESS = "ADD_DATA_TO_CART_SUCCESS";
export const ADD_DATA_TO_CART_FAILURE = "ADD_DATA_TO_CART_FAILURE";

export const GET_DATA_FROM_CART_REQ = "GET_DATA_FROM_CART_REQ";
export const GET_DATA_FROM_CART_SUCCESS = "GET_DATA_FROM_CART_SUCCESS";
export const GET_DATA_FROM_CART_FAILURE = "GET_DATA_FROM_CART_FAILURE";

export const DELETE_DATA_FROM_CART = "DELETE_DATA_FROM_CART";
export const CLEAR_CART_DATA = "CLEAR_CART_DATA";
