
export const GET_DATE_SELECTOR_SUCCESS = 'GET_DATE_SELECTOR_SUCCESS';
export const GET_DATE_SELECTOR_FAILURE = 'GET_DATE_SELECTOR_FAILURE';
export const GET_DATE_SELECTOR_REQUEST = 'GET_DATE_SELECTOR_REQUEST';

export const POST_DATE_SELECTOR_SUCCESS = 'POST_DATE_SELECTOR_SUCCESS';
export const POST_DATE_SELECTOR_FAILURE = 'POST_DATE_SELECTOR_FAILURE';
export const POST_DATE_SELECTOR_REQUEST = 'POST_DATE_SELECTOR_REQUEST';

