export const GET_DATE_SELECTOR_SUCCESS = 'GET_DATE_SELECTOR_SUCCESS';
export const GET_DATE_SELECTOR_FAILURE = 'GET_DATE_SELECTOR_FAILURE';
export const GET_DATE_SELECTOR_REQUEST = 'GET_DATE_SELECTOR_REQUEST';
